import { parse as parseYaml, stringify as stringifyYaml } from 'yaml'
import { BadRequestError, parseNoteId } from '@mnemonima/core'
import type { NoteStatus } from '@mnemonima/core'

/**
 * The exported frontmatter — DESIGN.md 5.1.
 *
 * Two halves, and the split is the whole design:
 *
 *  - **Authoritative** fields are read back on import. They are the ones a
 *    human can meaningfully edit in Obsidian: the title, the tags, the aliases,
 *    the terms entered by hand.
 *  - **Generated** fields — `keywords_auto`, `phrases_auto`, `outline`, `links`,
 *    `backlinks` — are written for the reader and for Obsidian, and **ignored
 *    completely on import**. They are derived from the body, so treating them as
 *    input would create a second source of truth and a permanent supply of
 *    conflicts.
 *
 * `rev` and `body_hash` travel with the file so import can tell an edit from a
 * conflict without guessing.
 */

export interface AuthoritativeFrontmatter {
  readonly id: string
  readonly title: string
  readonly status: NoteStatus
  readonly rev: number
  readonly created: string
  readonly updated: string
  readonly bodyHash: string
  readonly tags: readonly string[]
  readonly aliases: readonly string[]
  readonly keywordsManual: readonly string[]
  readonly phrasesManual: readonly string[]
}

export interface GeneratedFrontmatter {
  readonly keywordsAuto?: readonly string[]
  readonly phrasesAuto?: readonly string[]
  readonly outline?: string | null
  readonly links?: readonly string[]
  readonly backlinks?: readonly string[]
}

export interface ExportedNote {
  readonly frontmatter: AuthoritativeFrontmatter
  readonly generated: GeneratedFrontmatter
  readonly body: string
}

const MARKER = '---'

/** The line that separates what import reads from what it ignores. */
const GENERATED_NOTICE =
  'generated by mnemonima; edits below this line are discarded on import'

export function renderFrontmatter(note: ExportedNote): string {
  const authoritative: Record<string, unknown> = {
    id: note.frontmatter.id,
    title: note.frontmatter.title,
    status: note.frontmatter.status,
    rev: note.frontmatter.rev,
    created: note.frontmatter.created,
    updated: note.frontmatter.updated,
    body_hash: note.frontmatter.bodyHash,
  }

  if (note.frontmatter.tags.length > 0) authoritative['tags'] = [...note.frontmatter.tags]
  if (note.frontmatter.aliases.length > 0) authoritative['aliases'] = [...note.frontmatter.aliases]
  if (note.frontmatter.keywordsManual.length > 0) {
    authoritative['keywords_manual'] = [...note.frontmatter.keywordsManual]
  }
  if (note.frontmatter.phrasesManual.length > 0) {
    authoritative['phrases_manual'] = [...note.frontmatter.phrasesManual]
  }

  const generated: Record<string, unknown> = {}
  if (note.generated.keywordsAuto?.length) generated['keywords_auto'] = [...note.generated.keywordsAuto]
  if (note.generated.phrasesAuto?.length) generated['phrases_auto'] = [...note.generated.phrasesAuto]
  if (note.generated.outline != null && note.generated.outline !== '') {
    generated['outline'] = note.generated.outline
  }
  if (note.generated.links?.length) generated['links'] = [...note.generated.links]
  if (note.generated.backlinks?.length) generated['backlinks'] = [...note.generated.backlinks]

  const parts = [MARKER, stringifyYaml(authoritative).trimEnd()]

  if (Object.keys(generated).length > 0) {
    parts.push('', `# ${GENERATED_NOTICE}`, stringifyYaml(generated).trimEnd())
  }

  parts.push(MARKER, '', note.body.trimEnd(), '')
  return parts.join('\n')
}

export interface ParsedFile {
  /** Null when the file carries no frontmatter at all. */
  readonly frontmatter: Partial<AuthoritativeFrontmatter> | null
  readonly body: string
}

/**
 * Reads a file back.
 *
 * Only the authoritative keys are extracted; everything else in the block is
 * dropped on the floor, including anything a plugin decided to add. Being
 * relaxed here is deliberate — the file has been through Obsidian, and refusing
 * it because of an unfamiliar key would make the bridge useless.
 */
export function parseFile(source: string): ParsedFile {
  const normalised = source.replace(/^﻿/, '')

  if (!normalised.startsWith(`${MARKER}\n`) && !normalised.startsWith(`${MARKER}\r\n`)) {
    return { frontmatter: null, body: normalised.trim() }
  }

  const end = normalised.indexOf(`\n${MARKER}`, MARKER.length)
  if (end < 0) return { frontmatter: null, body: normalised.trim() }

  const block = normalised.slice(MARKER.length + 1, end)
  const body = normalised.slice(end + MARKER.length + 1).replace(/^\r?\n/, '')

  let parsed: unknown
  try {
    parsed = parseYaml(block)
  } catch (cause) {
    throw new BadRequestError('the frontmatter is not valid YAML', {
      details: { cause: String(cause) },
      hint: 'fix the block between the --- markers, or delete it to import the body alone',
    })
  }

  if (parsed === null || typeof parsed !== 'object') return { frontmatter: null, body: body.trim() }

  const record = parsed as Record<string, unknown>
  const id = typeof record['id'] === 'string' ? record['id'] : undefined

  return {
    frontmatter: {
      ...(id === undefined ? {} : { id }),
      ...(typeof record['title'] === 'string' ? { title: record['title'] } : {}),
      ...(isStatus(record['status']) ? { status: record['status'] } : {}),
      ...(typeof record['rev'] === 'number' ? { rev: record['rev'] } : {}),
      ...(typeof record['body_hash'] === 'string' ? { bodyHash: record['body_hash'] } : {}),
      tags: stringList(record['tags']),
      aliases: stringList(record['aliases']),
      keywordsManual: stringList(record['keywords_manual']),
      phrasesManual: stringList(record['phrases_manual']),
    },
    body: body.trim(),
  }
}

function isStatus(value: unknown): value is NoteStatus {
  return value === 'active' || value === 'draft' || value === 'archived'
}

function stringList(value: unknown): string[] {
  if (Array.isArray(value)) {
    return value.filter((entry): entry is string => typeof entry === 'string').map((entry) => entry.trim())
  }
  // Obsidian writes a single tag without a list.
  if (typeof value === 'string' && value.trim() !== '') return [value.trim()]
  return []
}

/**
 * `SL-0042 Shaders introduction.md`.
 *
 * The id leads so that resolution reads the leading token and does not depend
 * on the title, while the title is still there for a human browsing a folder and
 * for Obsidian's own `[[wikilink]]` completion.
 */
export function exportFilename(id: string, title: string): string {
  const clean = title
    .replace(/[\\/:*?"<>|]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 120)

  return clean === '' ? `${id}.md` : `${id} ${clean}.md`
}

/** The id a filename claims, for matching a file to a note before parsing it. */
export function idFromFilename(filename: string): string | null {
  const stem = filename.replace(/\.md$/i, '')
  const leading = stem.split(/\s+/)[0] ?? ''
  return parseNoteId(leading) === null ? null : leading
}
